name: 'Run Terraform'
description: 'Execute Terraform for an input client folder.'
inputs:
  repository:
    description: 'Name of the repository from which to check out'
  client:
    description: 'Client folder to check out and run'
    required: 'true'
runs:
  using: 'composite'
  steps:
  # Checkout the repository to the GitHub Actions runner
  - name: Checkout
    uses: actions/checkout@v3
    with:
      repository: inputs.repository
      path: ./inputs.client

  # Install the preferred version of Terraform CLI 
  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v2
    with:
      terraform_version: 1.1.7

  # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
  - name: Terraform Init
    id: init
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    run: terraform init 

    # On push to main, build or change infrastructure according to Terraform configuration files
  - name: Terraform Apply
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    run: terraform apply -auto-approve