name: Deployment TF Reuse
on:  
  workflow_dispatch:
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - name: Get Repository Code
      uses: actions/checkout@v3
    - name: Show Files
      run: ls -l -R
  walm:
    needs: prepare
    uses: WolfgangBaeck/REB3Azure/.github/workflows/reuse-terraform.yml@main
    with:
      working-folder: r3us-walm
