name: Deployment TF Reuse
on:  
  workflow_dispatch:
jobs:
  walm:
    name: Deploy to Dev
    uses: ./.github/workflows/reuse-terraform.yml
    with:
      environment: Development
      working-folder: r3us-walm
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ACID }}
      ARM_CLIENT_SECRET: ${{ secrets.ACS }}
      ARM_TENANT_ID: ${{ secrets.ATID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ASID }}    
      
  deploy_prod:
    name: Deploy to Prod
    needs: walm
    uses: ./.github/workflows/reuse-terraform.yml
    with:
      environment: UAT
      working-folder: r3us-dev
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ACID }}
      ARM_CLIENT_SECRET: ${{ secrets.ACS }}
      ARM_TENANT_ID: ${{ secrets.ATID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ASID }}    

