name: Deployment TF Reuse
on:  
  workflow_dispatch:
jobs:
  walm:
    name: Deploy to UAT
    uses: ./.github/workflows/reuse-terraform.yml
    with:
      environment: UAT
      working-folder: r3us-walm
    secrets:
      inherit


