name: Deployment Composite
on:
  workflow_dispatch:
jobs:
  walm:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository Code
        uses: actions/checkout@v3
      - name: Show Files
        run: ls -l -R
      - name: Call Terraform Composite Action
        uses: ./.github/actions/terraform
          with: "r3us-walm"
