name: Deployment
on:
  workflow_dispatch:
jobs:
  delta:
    runs-on: ubuntu-latest
    steps:
      - name: Get code for delta client
        uses: Bhacaz/checkout-files@v2
        with:
          files: r3us-delta
      - name: Get code from modules folder
        uses: Bhacaz/checkout-files@v2
        with:
          files: modules
      - name: Output filesystem
        run: ls -R