name: Deployment TF Reuse
on:  
  workflow_dispatch:
jobs:
  walm:
    environment: Development
    uses: ./.github/workflows/reuse-terraform.yml
    with:
      working-folder: r3us-walm
      secrets:
        ACID: ${{ secrets.ARM_CLIENT_ID }}
        ACS: ${{ secrets.ARM_CLIENT_SECRET }}
        ATID: ${{ secrets.ARM_TENANT_ID }}
        ASID: ${{ secrets.ARM_SUBSCRIPTION_ID }}    

