name: Deployment TF Reuse
on:  
  workflow_dispatch:
jobs:
  walm:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository Code
        uses: actions/checkout@v3

      - name: Show Filesystem
        run: ls -R

      - name: Use TF Workflow
        uses: WolfgangBaeck/REB3Azure/.github/workflows/reuse-terraform.yml@main
        with:
          working-folder: r3us-walm
