name: Dev-Deploy-All
on:  
  workflow_dispatch:
jobs:
  epsilon:
    name: Deploy Epsilon
    uses: ./.github/workflows/deploy.yml
    with:
      environment: Development
      working-folder: r3dev-epsilon
    secrets:
      inherit      