name: Dev-Destroy-All
on:  
  workflow_dispatch:
jobs:
  walm:
    name: Destroy development
    uses: ./.github/workflows/destroy.yml
    with:
      environment: Development
      working-folder: r3us-walm
    secrets:
      inherit