name: Dev-Destroy-All
on:  
  workflow_dispatch:
jobs:
  epsilon:
    name: Destroy Epsilon
    uses: ./.github/workflows/destroy.yml
    with:
      environment: Development
      working-folder: r3dev-epsilon
    secrets:
      inherit      
