name: Dev-Deploy-All
on:  
  workflow_dispatch:
jobs:
  walm:
    name: Deploy to Development
    uses: ./.github/workflows/deploy.yml
    with:
      environment: Development
      working-folder: r3us-walm
    secrets:
      inherit


