name: Reusable Terraform Action
on: 
  workflow_call:
    inputs:
      environment:
        description: "Environment context in which to run the Terraform process."
        required: true    
        type: string
      working-folder:
        description: The name of the client folder to process
        required: true
        type: string
      secrets:
        PASSWORD:
          required: true
        ARM_CLIENT_ID: 
          required: true
        ARM_CLIENT_SECRET: 
          required: true
        ARM_TENANT_ID: 
          required: true
        ARM_SUBSCRIPTION_ID: 
          required: true

env:
  ARM_CLIENT_ID: ${{ secrets.ACID }}
  ARM_CLIENT_SECRET: ${{ secrets.ACS }}
  ARM_TENANT_ID: ${{ secrets.ATID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ASID }}            
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  Terraform:
    name: Terraform deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working-folder }}

    steps:
      - name: Show password
        run: |
          echo Password is $PASSWORD
          if [[ $PASSWORD == *"password"* ]]; then
            echo "This is the UAT password!"
          else
            echo "This is NOT the UAT password!"
          fi
      - name: Get Repository Code
        uses: actions/checkout@v3
      - name: Show Files
        run: ls -l -R
      # Install the preferred version of Terraform CLI 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7
      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init 

      # Run a terraform apply 
      - name: Terraform apply
        id: plan
        run: terraform apply -auto-approve