
name: Deploy Pipeline

on:
  workflow_dispatch:

jobs:
  deploy_dev:
    name: Deploy to Dev
    uses: ./.github/workflows/reuse.yml
    with:
      environment: Development
    secrets:
      inherit
      
  deploy_prod:
    name: Deploy to UAT
    needs: deploy_dev
    uses: ./.github/workflows/reuse.yml
    with:
      environment: UAT
    secrets:
      inherit

